server:
  port: 8080
spring:
  data:
    mongodb:
      database: pixiv-illustration-collection
      uri: mongodb://127.0.0.1:27017/pixiv-illustration-collection
  mail:
    host: smtp.qq.com
    username: 403827354@qq.com
    password: mgysdtrrgxzsbhie
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
pixiv:
  client_id: KzEZED7aC0vird8jWyHM38mXjNTY
  client_secret: W9JZoJe00qPvJsiyCGT3CCtC6ZUtdpKpzMbNlUGP
  username: 392822872@qq.com
  password: Linhao199741
  device_token: fb12e7c1945000850deb5f7001c02745
  refresh_token: 07FHA5xA6NkOIxIayqm3tZbJqxbypDJHrXguT7cazLI
client:
  checkWord: oysterqaq